### ISSUE TITLE
Unable to get microservice running on Flutter 1.7 and 1.9 Android

### ISSUE THREAD

**Issue by carlosjrtee** [j0j00/flutter_liquidcore#5]
I'm running into this error after clicking the MicroService button in your example application:

`Launching lib/main.dart on Lenovo S90 A in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/View    (21783): Touch down dispatch to io.flutter.view.FlutterView{10898e14 VFE..... .F...... 0,0-720,1280}, event = MotionEvent { action=ACTION_DOWN, id[0]=0, x[0]=399.44522, y[0]=336.73694, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=114429104, downTime=114429104, deviceId=7, source=0x1002 }
I/View    (21783): Touch up dispatch to io.flutter.view.FlutterView{10898e14 VFE..... .F...... 0,0-720,1280}, event = MotionEvent { action=ACTION_UP, id[0]=0, x[0]=399.44522, y[0]=336.73694, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=114429310, downTime=114429104, deviceId=7, source=0x1002 }
I/mkdir   (21783): Created directory /data/data/io.jojodev.flutter.liquidcoreexample/cache/__org.liquidplayer.node__/sessions/696636ad-fe38-49af-b84b-e882fbac8b49/home
I/mkdir   (21783): Created directory /data/data/io.jojodev.flutter.liquidcoreexample/cache/__org.liquidplayer.node__/sessions/696636ad-fe38-49af-b84b-e882fbac8b49/temp
W/System.err(21783): java.lang.reflect.InvocationTargetException
W/System.err(21783): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(21783): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(21783): 	at org.liquidplayer.javascript.JSFunction.function(JSFunction.java:516)
W/System.err(21783): 	at org.liquidplayer.javascript.JSFunction.functionCallback(JSFunction.java:466)
W/System.err(21783): 	at org.liquidplayer.node.Process.runInThread(Native Method)
W/System.err(21783): 	at org.liquidplayer.node.Process.access$100(Process.java:23)
W/System.err(21783): 	at org.liquidplayer.node.Process$1.run(Process.java:110)
W/System.err(21783): 	at java.lang.Thread.run(Thread.java:818)
W/System.err(21783): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: nodejs
W/System.err(21783): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
W/System.err(21783): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
W/System.err(21783): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
W/System.err(21783): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
W/System.err(21783): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
W/System.err(21783): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
W/System.err(21783): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
W/System.err(21783): 	at io.jojodev.flutter.liquidcore.handler.MicroServiceHandler$MicroServiceListener.onStart(MicroServiceHandler.java:164)
W/System.err(21783): 	at io.jojodev.flutter.liquidcore.components.WrappedMicroService$1.onStart(WrappedMicroService.java:37)
W/System.err(21783): 	at org.liquidplayer.service.MicroService.onProcessStart(MicroService.java:790)
W/System.err(21783): 	at org.liquidplayer.node.Process.eventOnStart(Process.java:216)
W/System.err(21783): 	at org.liquidplayer.node.Process.access$1000(Process.java:23)
W/System.err(21783): 	at org.liquidplayer.node.Process$3.__nodedroid_onLoad(Process.java:349)
W/System.err(21783): 	... 8 more
W/System.err(21783): Error: java.lang.reflect.InvocationTargetException
W/System.err(21783): 	at org.liquidplayer.javascript.JSFunction.function(JSFunction.java:526)
W/System.err(21783): 	at org.liquidplayer.javascript.JSFunction.functionCallback(JSFunction.java:466)
W/System.err(21783): 	at org.liquidplayer.node.Process.runInThread(Native Method)
W/System.err(21783): 	at org.liquidplayer.node.Process.access$100(Process.java:23)
W/System.err(21783): 	at org.liquidplayer.node.Process$1.run(Process.java:110)
W/System.err(21783): 	at java.lang.Thread.run(Thread.java:818)
I/Unhandled(21783): There is an unhandled exception!
I/Unhandled(21783): Error: java.lang.reflect.InvocationTargetException
I/Unhandled(21783): [eval]:1
I/Unhandled(21783): global.__nodedroid_onLoad();
I/Unhandled(21783):        ^
I/Unhandled(21783):
I/Unhandled(21783): Error: java.lang.reflect.InvocationTargetException
I/Unhandled(21783):     at [eval]:1:8
I/Unhandled(21783):     at ContextifyScript.Script.runInThisContext (vm.js:50:33)
I/Unhandled(21783):     at Object.runInThisContext (vm.js:139:38)
I/Unhandled(21783):     at Object.<anonymous> ([eval]-wrapper:6:22)
I/Unhandled(21783):     at Module._compile (module.js:635:30)
I/Unhandled(21783):     at evalScript (bootstrap_node.js:462:27)
I/Unhandled(21783):     at startup (bootstrap_node.js:163:9)
I/Unhandled(21783):     at bootstrap_node.js:608:3
D/NodeInstance(21783): exit(-1) called
I/sessionWatchdog(21783): deleting session /data/data/io.jojodev.flutter.liquidcoreexample/cache/__org.liquidplayer.node__/sessions/696636ad-fe38-49af-b84b-e882fbac8b49
`
I tried running on both Flutter 1.7 and 1.9, using the simulator and an android device.

[✓] Flutter (Channel unknown, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale
    en-PH)
    • Flutter version 1.7.8+hotfix.4 at /Users/cormant/Applications/flutter
    • Framework revision 20e59316b8 (2 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cormant/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.8.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • Lenovo S90 A • ffc1d89e • android-arm64  • Android 5.0.2 (API 21)
    • macOS        • macOS    • darwin-x64     • Mac OS X 10.14.6 18G95
    • web          • web      • web-javascript • Google Chrome 77.0.3865.90 

• No issues found!

[✓] Flutter (Channel master, v1.10.6-pre.29, on Mac OS X 10.14.6 18G95, locale
    en-PH)
    • Flutter version 1.10.6-pre.29 at /Users/cormant/Applications/flutter
    • Framework revision 919cc97f6a (9 days ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cormant/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Lenovo S90 A • ffc1d89e • android-arm64 • Android 5.0.2 (API 21)

• No issues found!

**Comment by j0j00** [comment]
Can you please re-upload your stacktrace as a gist or something as well as specify which version of Liquidcore and Liquidcore plugin you're running.

**Comment by j0j00** [comment]
Closing due to lack of activity.
Feel free to reopen if you're still having issues, and you're sure that it's a issue specific to this plugin rather than the Liquidcore library itself.

**Comment by cashdow** [comment]
I have the same issue. same error message.

Use flutter v1.7~, v.1.9 same.

I used liquidcore_sample.js (your example flie). but It's started when invoked microservice.start()
